import type { Metadata } from "next";

import { Montserrat} from "next/font/google";

import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import Question from "./components/footer/question/Question";

const montserrat = Montserrat({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header />
        
        <div className="">
          {children}
        </div>
        <Question />
        <Footer />
      </body>
    </html>
  );
}
